### ISSUE TITLE
Opening the bot

### ISSUE THREAD

**Issue by Eeman1113** [dzakyputra/doggobot#2]
![Screenshot_2020-02-11-00-20-32-818_ru iiec pydroid3](https://user-images.githubusercontent.com/54275491/74182341-e0cc0c00-4c68-11ea-8144-98b8c68c88a6.jpg)
Error please help

**Comment by dzakyputra** [comment]
you should change 'YOUR TOKEN' into your telegram bot token

first, create your bot in https://telegram.me/botfather then generate the token there
