### ISSUE TITLE
Error when data is submitted

### ISSUE THREAD

**Issue by Tech-Matt** [dzakyputra/doggobot#3]
Whenever a command is submitted into the Telegram bot I got this error.

![Screenshot from 2020-08-22 11-28-10](https://user-images.githubusercontent.com/30274868/90953341-cae6a180-e46a-11ea-99e8-ee80ee8fa936.png)

**Comment by dzakyputra** [comment]
> Whenever a command is submitted into the Telegram bot I got this error.
> 
> ![Screenshot from 2020-08-22 11-28-10](https://user-images.githubusercontent.com/30274868/90953341-cae6a180-e46a-11ea-99e8-ee80ee8fa936.png)

Based on the error, I think it is because of the parenthesis, can you check again all the parenthesis have opening and ending
