### ISSUE TITLE
About deploying the bot to heroku 

### ISSUE THREAD

**Issue by HEMANTHNARRAXDA** [dzakyputra/doggobot#4]
Please also write an article about how to deploy the bot to the heroku

**Comment by kibablu** [comment]
> Please also write an article about how to deploy the bot to the heroku

@HEMANTHNARRAXDA you can look into this for Heroku part https://thenextweb.com/syndication/2020/05/27/a-step-by-step-guide-to-building-your-first-telegram-bot/

**Comment by dzakyputra** [comment]
> > Please also write an article about how to deploy the bot to the heroku
> 
> @HEMANTHNARRAXDA you can look into this for Heroku part https://thenextweb.com/syndication/2020/05/27/a-step-by-step-guide-to-building-your-first-telegram-bot/

Thank you very much for the response @kibablu !

@HEMANTHNARRAXDA you can check the link provided
